create product
alcalati/Backend pull request #16
Opened 2024-06-21 18:54 UTC by alba-garcia09

2024-06-26 18:09 UTC, JonaTheBridge requested changes

2024-06-26 18:09 UTC, JonaTheBridge commented on src/api/clothes/clothes.controller.js
> +  if(clothesItem.stock){
Te lo pongo como mejora de rendimiento pero no es necesario hacer cambios: de nada sirve inicializar el stock a cero si luego hay campos vacíos que son obligatorios. Yo primero comprobaría esos campos y si veo que está todo bien, inicializo el stock a cero. Es una mejora de rendimiento mínima pero puede hacerse y mola que empecéis a pensar este tipo de cosas.

2024-06-26 18:09 UTC, JonaTheBridge commented on src/api/clothes/clothes.router.js
> +
esta linea en blanco no es necesaria

2024-06-26 18:48 UTC, JonaTheBridge approved these changes

2024-06-28 11:54 UTC, PauloTorrente approved these changes

2024-06-28 16:55 UTC, alcalati approved these changes
nice work

2024-06-28 16:57 UTC, merged