modify-clothes
alcalati/Backend pull request #17
Opened 2024-06-25 16:21 UTC by PauloTorrente

ahora se puede modificar los productos atraves de ID

2024-06-27 17:19 UTC, alba-garcia09 commented
You have still conflicts

2024-06-28 16:45 UTC, PauloTorrente commented
Ya resolvi las dferencias, pueden chequear si está bien

2024-06-28 16:47 UTC, JonaTheBridge requested changes

2024-06-28 16:47 UTC, JonaTheBridge commented on src/api/clothes/clothes.controller.js
> +    const updatedProduct = await clothesService.updateById(id, updateData);
sería mejor que lo hicieses con named params

2024-06-28 16:47 UTC, JonaTheBridge commented on src/api/clothes/clothes.service.js
> +  const updatedProduct = await clothesRepository.updateById(id, updateData);
sería mejor que lo hicieses con named params

2024-06-28 17:36 UTC, alcalati reviewed
looks nice

2024-06-28 17:52 UTC, JonaTheBridge approved these changes

2024-06-28 18:04 UTC, alba-garcia09 approved these changes

2024-06-28 18:06 UTC, alcalati approved these changes

2024-06-28 18:06 UTC, merged