Route to get cash
alcalati/Backend pull request #20
Opened 2024-06-28 18:46 UTC by alba-garcia09

2024-06-28 18:47 UTC, alba-garcia09 commented
Es el mismo pull request y ya se ha actualizado

2024-06-29 07:58 UTC, PauloTorrente approved these changes

2024-06-29 08:00 UTC, JonaTheBridge requested changes

2024-06-29 08:00 UTC, JonaTheBridge commented on src/api/users/users.router.js
> +export default router;
deja una linea en blanco al final de cada fichero

2024-06-29 08:00 UTC, JonaTheBridge commented on src/api/users/users.service.js
> +}
deja una linea en blanco al final de cada fichero

2024-06-29 08:00 UTC, alcalati approved these changes

2024-06-29 08:36 UTC, merged